export { default as apiClient } from './client/index.js'
export { AuthService } from './services/auth.service.js'
export { CoursesService } from './services/courses.service.js'
export { TeacherModulesService } from './services/teacherModules.service.js'
export { NotificationsService } from './services/notifications.service.js'
export { StudentPeopleService } from './services/studentPeople.service.js'
export { ProfileService } from './services/profile.service.js'
