export function backendToUser(b) {
  if (!b) return null
  return {
    id: b.id_usuario ?? b.id ?? null,
    codigo: b.codigo ?? '',
    nombre: b.nombre ?? '',
    apellido: b.apellido ?? '',
    correo: b.correo ?? b.email ?? '',
    rol: b.rol ?? b.role ?? 'alumno',
    grado: b.grado ?? null,
    telefono: b.telefono ?? '',
    direccion: b.direccion ?? '',
    fechaNacimiento: b.fecha_nacimiento ?? b.fechaNacimiento ?? '',
    genero: b.genero ?? '',
    documentoIdentidad: b.documento_identidad ?? b.documentoIdentidad ?? '',
    avatarUrl: b.url_foto ?? b.avatarUrl ?? '',
    biografia: b.biografia ?? b.bio ?? '',
    apoderadoNombre: b.apoderado_nombre ?? b.apoderadoNombre ?? '',
    apoderadoParentesco: b.apoderado_parentesco ?? b.apoderadoParentesco ?? '',
    apoderadoTelefono: b.apoderado_telefono ?? b.apoderadoTelefono ?? '',
    apoderadoCorreo: b.apoderado_correo ?? b.apoderadoCorreo ?? '',
    apoderadoDocumento: b.apoderado_documento ?? b.apoderadoDocumento ?? '',
    contactoEmergenciaNombre: b.contacto_emergencia_nombre ?? b.contactoEmergenciaNombre ?? '',
    contactoEmergenciaParentesco: b.contacto_emergencia_parentesco ?? b.contactoEmergenciaParentesco ?? '',
    contactoEmergenciaTelefono: b.contacto_emergencia_telefono ?? b.contactoEmergenciaTelefono ?? '',
    condicionMedica: b.condicion_medica ?? b.condicionMedica ?? '',
    alergias: b.alergias ?? '',
    observaciones: b.observaciones ?? '',
    fechaRegistro: b.fecha_registro ?? b.fechaRegistro ?? '',
  }
}
